### ISSUE TITLE
[FIX] 사전 로딩으로 발생된 suspense의 중단으로 인한 error

### ISSUE THREAD

**Issue by jihwan1211** [prgrms-fdc-2nd-final-mosdaq/mosdaq-front#71]
## 어떤 문제인가요?

> 사전 로딩으로 발생된 suspense의 중단으로 인한 error

## 문제 발생 상황?

> 헤더 컴포넌트에 마우스를 올렸을 때 사전로딩을 진행하며 suspense가 발생되는데, 해당 suspense가 완료되기 전에 Link동작이 일어나면 suspense가 중단 되면서 에러가 발생됨. 
-> 리액트의 startTransition 으로 해결 가능함

## 해결 방안

> 헤더의 Link를 모두 useNavigate로 래핑해서 사용하는 방향으로 해결 가능 
아래 gpt가 제시한 대로 해보니까 에러가 안 나긴 합니다.

## 참고할만한 자료(선택)
https://kimsangyeon-github-io.vercel.app/blog/2022-02-03-react-startTransition

gpt 답변

네, Link로 페이지를 이동할 때도 이 문제가 발생할 수 있습니다. React Router의 Link 컴포넌트를 사용하여 페이지를 이동하는 경우에도, 페이지 전환 과정에서 새로운 컴포넌트가 로드되면서 Suspense가 발생하면 "suspended while responding to synchronous input" 오류가 발생할 수 있습니다.

왜 Link로 페이지 이동할 때 문제가 발생하나요?
React Router의 Link 컴포넌트를 클릭하여 페이지를 이동하면, 해당 페이지의 컴포넌트가 로드됩니다. 만약 이 과정에서 lazy-loaded 컴포넌트를 사용하고, 컴포넌트가 로딩되는 동안 Suspense에 의해 로딩 스피너가 표시된다면, React는 이를 사용자 인터랙션(즉, 링크 클릭)에 대한 응답 중에 suspend된 것으로 간주합니다.

이 경우에도 React는 동기적인 사용자 입력에 반응하여 UI가 로딩 상태로 전환되는 것을 방지하고자 경고를 발생시킵니다.

해결 방법
Link를 클릭할 때 발생하는 이 문제를 해결하기 위해, React Router의 페이지 전환도 startTransition으로 래핑할 수 있습니다. 이를 통해 페이지 전환이 우선 순위가 낮은 전환으로 처리되도록 하여, UI가 부드럽게 전환되도록 합니다.

적용 방법
Link 컴포넌트를 클릭할 때 startTransition을 사용할 수 있도록 수정하는 방법은 다음과 같습니다:

javascript
코드 복사
import { startTransition } from 'react';
import { useNavigate } from 'react-router-dom';

function MyComponent() {
  const navigate = useNavigate();

  function handleClick() {
    startTransition(() => {
      navigate('/new-page');
    });
  }

  return <button onClick={handleClick}>Go to New Page</button>;
}
위 예제에서 useNavigate 훅과 startTransition을 사용하여 페이지 전환을 래핑했습니다. 이로써 페이지 전환이 React의 낮은 우선 순위로 처리되며, 사용자 인터랙션과 관련된 동기 입력이 suspend될 때 발생하는 오류를 방지할 수 있습니다.

React Router v6에서 Link 컴포넌트에 startTransition 적용
React Router v6에서는 Link 컴포넌트 자체에서 startTransition을 적용할 수는 없지만, 위에서 설명한 것처럼 useNavigate를 사용하여 페이지 전환을 처리하고, 그 페이지 전환을 startTransition으로 래핑하는 방법을 사용할 수 있습니다.

만약 전체 애플리케이션에서 페이지 전환을 일관되게 startTransition으로 처리하려면, 모든 Link 컴포넌트를 이렇게 커스텀 버튼으로 교체하거나, Link 컴포넌트를 커스터마이즈하여 전역적으로 사용하게 할 수 있습니다.

**Comment by javascriptbiggosoo** [comment]
에러가 있었군요. 해결하면서 사전로딩도 문제없이 되는지 확인 가능한가요?

**Comment by jihwan1211** [comment]
> 에러가 있었군요. 해결하면서 사전로딩도 문제없이 되는지 확인 가능한가요?

넵 usenavigate로 바꿔도 마우스 올릴 때 네트워크 요청 가는거 보입니다. 그러면 사전 로딩 되는거 아닌가요?

**Comment by javascriptbiggosoo** [comment]
> > 에러가 있었군요. 해결하면서 사전로딩도 문제없이 되는지 확인 가능한가요?
> 
> 넵 usenavigate로 바꿔도 마우스 올릴 때 네트워크 요청 가는거 보입니다. 그러면 사전 로딩 되는거 아닌가요?

해결 감사합니당

**Comment by jihwan1211** [comment]
아직 적용은 안 해서 나중에 브랜치 파서 적용하겠습니다!
